services:

  bank-postgres:
    image: postgres:17.2-alpine3.21
    ports:
      - 6432:5432
    environment:
      environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: "trust"

  bank-adminer:
    image: adminer:4.8.1
    ports:
      - 8081:8080

  bank-go-app:
    working_dir: /go-app-dir
    environment:
      - GO_HOST=${GO_HOST}
      - GO_DB_URL=${GO_DB_URL}
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/go-app-dir
    ports:
      - "8080:8080"
